#!/usr/bin/env python3
# This program compiles an AQASM file into a job or a batch file.

# qc test.aqasm 
# qat-jobrun --qpu qat.pylinalg:PyLinalg test.aqasm.job

# A tool to do this seems to be missing from the QLM/docs?

# Owain Kenway, 2022

# Dump out a job.
def gen_job(circuit, outfile):
	out_job = circuit.to_job()
	print("Writing output file: " + outfile)
	out_job.dump(outfile)

# This is an annoying way of doing things but:
# The errors produced by aqasm2circ imply it is python, which is good.
# BUT: the parts of MyQLM that generate circuits from aqasm are not 
# documented so we must assume they are closed source and we may not
# look at them, so despite being in python and there probably being 
# a library call we can make to do this directly, we go this circuitous
# route of subprocess for license reasons :(
def run_aqasm2circ(infile, fm, ndg, ni, modules):
	import tempfile
	import os.path
	import subprocess
	from qat.core import Circuit

	td = tempfile.mkdtemp(prefix='qc_')
	outfilename = infile + ".circ"
	outfile = os.path.join(td, outfilename)

	print("Temporary output file: " + outfile)

	command_line = ['aqasm2circ']
	if fm:
		command_line.append('--full-matrices')
	if ndg: 
		command_line.append('--no-default-gateset')
	if ni: 
		command_line.append('--no-inline')

	for a in modules:
		command_line.append(' -L ')
		command_line.append(a)

	command_line.append(infile)
	command_line.append(outfile)

	print("aqasm2circ command: " + str(command_line))

	status = subprocess.run(command_line, capture_output=True, encoding='UTF-8')

	if (status.returncode == 0):
		c = Circuit.load(outfile)
		os.remove(outfile)
		os.rmdir(td)
		return c
	else:
		raise OSError(status.stderr)
	
# Main function
if __name__ == '__main__':
	import argparse

	parser = argparse.ArgumentParser(description='Compile AQASM to jobs.')
	parser.add_argument('-o', metavar='filename', type=str, help='Output file.')
	parser.add_argument('-b', action='store_true', help='Generate a batch file instead.')
	parser.add_argument('--full-matrices', action='store_true', help='Passed to aqasm2circ.  See aqasm2circ --help for details.')
	parser.add_argument('--no-default-gateset', action='store_true', help='Passed to aqasm2circ.  See aqasm2circ --help for details.')
	parser.add_argument('--no-inline', action='store_true', help='Passed to aqasm2circ.  See aqasm2circ --help for details.')
	parser.add_argument('aqasm')
	args = parser.parse_args()

	infile = args.aqasm

	outfile = args.aqasm + '.job'
	if (args.o != None):
		outfile = args.o

	fm = False
	if (args.full_matrices != None):
		fm = args.full_matrices
	ndg = False
	if (args.no_default_gateset != None):
		ndg = args.no_default_gateset
	ni = False
	if (args.no_inline != None):
		ni = args.no_inline

	if infile != '':
		c = run_aqasm2circ(infile, fm, ndg, ni, [])
		gen_job(c, outfile)
	
