#!/usr/bin/env bash

set -e

QISKIT_VERSION=${QISKIT_VERSION:-0.19.6}


conda create --no-default-packages -n qiskitT2 python=3.7

# Thanks @BuckmasterFresh for this:
# https://twitter.com/BuckmasterFresh/status/1541746939099742209
source activate qiskitT2

pip3 install --upgrade pip
conda install ipython
conda install jupyter
conda install jupyterlab
conda install qtconsole
pip3 install qiskit==${QISKIT_VERSION}
pip3 install qiskit[visualization]==${QISKIT_VERSION}
